# -*- coding: utf-8 -*-
"""4-Hafta-Odev.ipynb

Automatically generated by Colab.
"""

import numpy as np
import pandas as pd

# Veri Yukleme
studentDf = pd.read_csv("student_performance_dataset.csv")
print("--- Veri Seti Ilk 5 Satir ---")
print(studentDf.head())

# Eksik Veri Tespiti (parental_education kolonu eksik)
print("\n--- Eksik Veri Sayilari ---")
print(studentDf.isnull().sum())

# Eksik Veri Temizleme (Mod ile doldurma)
educationMode = studentDf["parental_education"].mode()[0]
studentDf["parental_education"] = studentDf["parental_education"].fillna(educationMode)

print("\n--- Temizleme Sonrasi Eksik Veriler ---")
print(studentDf.isnull().sum())

# Indeksleme ve Filtreleme
print("\n--- Indeksleme (loc & iloc) ---")
print("10. indexteki ogrenci:")
print(studentDf.loc[10])

print("\nilk 3 ogrencinin ilk 5 kolonu:")
print(studentDf.iloc[:3, :5])

# Calisma suresi > 5 saat ve notu > 85 olanlar
print("\nFiltrelenmis Ogrenciler (Study Time > 5 & Previous Grade > 85):")
filteredStudents = studentDf[(studentDf["study_time_hours"] > 5) & (studentDf["previous_grade"] > 85)]
print(filteredStudents.head())

# Gruplandirma (GroupBy)
print("\n--- Aile Egitim Durumuna Gore Ortalamalar ---")
educationGroups = studentDf.groupby("parental_education")[["study_time_hours", "final_exam_score"]].mean()
print(educationGroups)
